### ISSUE TITLE
Example yaml file syntax is invalid since 0.14

### ISSUE THREAD

**Issue by hardys** [parca-dev/docs#199]
I followed https://www.parca.dev/docs/systemd which contains a yaml file example like:

```
debug_info:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: "/tmp"
  cache:
    type: "FILESYSTEM"
    config:
      directory: "/tmp"

scrape_configs:
  - job_name: "default"
    scrape_interval: "2s"
    static_configs:
      - targets: ["127.0.0.1:7070"]
```

However this fails to start, with an error like:

```
level=error name=parca ts=2022-11-22T10:51:43.582639041Z caller=main.go:59 msg="Program exited with error" err="parsing YAML file /etc/parca/parca.yaml: yaml: unmarshal errors:\n  line 1: field debug_info not found in type config.Config"
```

AFAICS this is because `debug_info` is no longer valid since https://github.com/parca-dev/parca/pull/1403 - instead I used a config like this:

```
object_storage:
  bucket:
    type: "FILESYSTEM"
    config:
      directory: "/tmp"

scrape_configs:
  - job_name: "default"
    scrape_interval: "2s"
    static_configs:
      - targets: ["127.0.0.1:7070"]
```
